//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt4.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.favorite = new HashSet<favorite>();
        }
        [DisplayName("Förnamn")]
        public string firstname { get; set; }
        [DisplayName("Efternamn")]
        public string lastname { get; set; }
        [DisplayName("E-post")]
        public string email { get; set; }
        [DisplayName("Användernamn")]
        public string username { get; set; }
        [DisplayName("Lösenord")]
        public string password { get; set; }
        public Nullable<int> admin { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favorite> favorite { get; set; }
    }
}
