//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt4.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public int Id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> account_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual channel channel { get; set; }
    }
}
