//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt4.Models.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Interaktiva_gAEntities : DbContext
    {
        public Interaktiva_gAEntities()
            : base("name=Interaktiva_gAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<channel> channel { get; set; }
        public virtual DbSet<favorite> favorite { get; set; }
        public virtual DbSet<genretype> genretype { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<program> program { get; set; }
        public virtual DbSet<programtype> programtype { get; set; }
    }
}
