//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt4.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class news
    {
        [DisplayName("Information")]
        public string information { get; set; }
        [DisplayName("Regissör")]
        public string director { get; set; }
        [DisplayName("Skådespelare")]
        public string actors { get; set; }
        public int id { get; set; }
       
        public Nullable<int> channel_id { get; set; }
    
        public virtual program program { get; set; }
    }
}
