//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt4.Models.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public program()
        {
            this.news = new HashSet<news>();
        }
    
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> programtype_id { get; set; }
        public Nullable<int> genre_id { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> finish { get; set; }
        [DisplayName("Namn")]
        public string name { get; set; }
        public int id { get; set; }
    
        public virtual channel channel { get; set; }
        public virtual genretype genretype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<news> news { get; set; }
        public virtual programtype programtype { get; set; }
    }
}
